# Generated by Django 5.0.2 on 2024-05-16 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=100)),
                ('correo_institucional', models.EmailField(max_length=254)),
                ('tipo_identificacion', models.CharField(choices=[('CC', 'C.C'), ('TI', 'T.I')], max_length=50)),
                ('numero_identificacion', models.CharField(max_length=50)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('tipo_servicio', models.CharField(choices=[('Grabacion', 'Grabación'), ('Entrega', 'Entrega')], max_length=20)),
                ('lugar_evento', models.CharField(blank=True, choices=[('1', 'Lugar 1'), ('2', 'Lugar 2'), ('3', 'Lugar 3')], max_length=50, null=True)),
                ('lugar_grabacion', models.CharField(blank=True, choices=[('1', 'Lugar 1'), ('2', 'Lugar 2'), ('3', 'Lugar 3')], max_length=50, null=True)),
                ('duracion_evento', models.DurationField(blank=True, null=True)),
                ('lugar_origen', models.CharField(blank=True, choices=[('1', 'Lugar 1'), ('2', 'Lugar 2'), ('3', 'Lugar 3')], max_length=100, null=True)),
                ('lugar_destino', models.CharField(blank=True, choices=[('1', 'Lugar 1'), ('2', 'Lugar 2'), ('3', 'Lugar 3')], max_length=100, null=True)),
                ('medidas_paquete', models.CharField(blank=True, max_length=50, null=True)),
                ('peso_paquete', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('correo_destinatario', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
    ]
