# Generated by Django 5.0.2 on 2024-05-16 21:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='duracion_evento',
            field=models.DurationField(blank=True, default=datetime.timedelta(seconds=3600), null=True),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='fecha',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='hora',
            field=models.TimeField(default=datetime.time(8, 0)),
        ),
    ]
